//Login
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

//Item List
export const LIST_ITEMS_REQUEST = "LIST_ITEMS_REQUEST";
export const LIST_ITEMS = "LIST_ITEMS";
export const LIST_ITEMS_FAIL = "LIST_ITEMS_FAIL";

//Transaction List
export const TRANSACTION_LIST_REQUEST = "TRANSACTION_LIST_REQUEST";
export const TRANSACTION_LIST = "TRANSACTION_LIST";
export const TRANSACTION_LIST_FAIL = "TRANSACTION_LIST_FAIL";

//Buy Items List
export const BUYITEM_LIST_REQUEST = "BUYITEM_LIST_REQUEST";
export const BUYITEM_LIST = "BUYITEM_LIST";
export const BUYITEM_LIST_FAIL = "BUYITEM_LIST_FAIL";

//Bid Items List
export const BIDITEM_LIST_REQUEST = "BIDITEM_LIST_REQUEST";
export const BIDITEM_LIST = "BIDITEM_LIST";
export const BIDITEM_LIST_FAIL = "BIDITEM_LIST_FAIL";

//Raffle Items List
export const RAFFLE_LIST_REQUEST = "RAFFLE_LIST_REQUEST";
export const RAFFLE_LIST = "RAFFLE_LIST";
export const RAFFLE_LIST_FAIL = "RAFFLE_LIST_FAIL";

//Token Balance
export const TOKEN_BALANCE_REQUEST = "TOKEN_BALANCE_REQUEST";
export const TOKEN_BALANCE = "TOKEN_BALANCE";
export const TOKEN_BALANCE_FAIL = "TOKEN_BALANCE_FAIL";

//Catogery Items
export const CATOGERY_ITEMS_REQUEST = "CATOGERY_ITEMS_REQUEST";
export const CATOGERY_ITEMS = "CATOGERY_ITEMS";
export const CATOGERY_ITEMS_FAIL = "CATOGERY_ITEMS_FAIL";

//Catogery Items
export const CLIENT_PROFILE_REQUEST = "CLIENT_PROFILE_REQUEST";
export const CLIENT_PROFILE_SUCCESS = "CLIENT_PROFILE_SUCCESS";
export const CLIENT_PROFILE_FAIL = "CLIENT_PROFILE_FAIL";
